
SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_OUTS O
JOIN (
    SELECT ANIMAL_ID, SEX_UPON_INTAKE
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE 'Intact%'
) I ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.SEX_UPON_OUTCOME LIKE 'Spayed%' or sex_upon_outcome like 'Neutered%'