-- 코드를 입력하세요

/*
SELECT J.FLAVOR
FROM JULY J
INNER JOIN FIRST_HALF F
ON J.SHIPMENT_ID = F.SHIPMENT_ID
GROUP BY FLAVOR
ORDER BY J.TOTAL_ORDER + F.TOTAL_ORDER
LIMIT 3;

*/ 

/*
SELECT J.FLAVOR
FROM JULY J
INNER JOIN FIRST_HALF F
ON J.SHIPMENT_ID = F.SHIPMENT_ID
GROUP BY J.FLAVOR
ORDER BY J.TOTAL_ORDER + F.TOTAL_ORDER DESC
LIMIT 3;
*/
SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_ORDER
    FROM JULY
    GROUP BY FLAVOR
) J ON F.FLAVOR = J.FLAVOR
ORDER BY (F.TOTAL_ORDER + J.JULY_ORDER) DESC
LIMIT 3;