/*
    보호 시작일(ANIMAL_INS) 보다 입양일(ANIMAL_OUT)이 더 빠른 동물 찾기
    -> 어느 테이블 기준? : 입양일 테이블에 있는 동물 중에서 서치해야 함!
*/

SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
FROM ANIMAL_OUTS
JOIN ANIMAL_INS ON ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID
WHERE ANIMAL_OUTS.DATETIME < ANIMAL_INS.DATETIME
ORDER BY ANIMAL_INS.DATETIME